modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="jaruso99"
description='''
Zapisuje ekwipunek i poziom doswiadczenia gracza przy smierci. Operatorzy moga przywrocic zapisany stan.
Wersja NeoForge dla Minecraft 1.21.1 (All The Mods 10).
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
